// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storegen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exchange struct {
	ID           string
	Scope        string
	State        string
	Participants []string
	OpenedAt     pgtype.Timestamptz
	ClosedAt     pgtype.Timestamptz
}

type PresenceEvent struct {
	ID        string
	Scope     string
	Voice     string
	Event     string
	Ts        pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type Settlement struct {
	ID         string
	ExchangeID string
	Scope      string
	Terms      []byte
	Parties    []string
	Ts         pgtype.Timestamptz
}

type Utterance struct {
	Seq     int64
	ID      string
	Ts      pgtype.Timestamptz
	Scope   string
	Payload []byte
}

type Voice struct {
	ID        string
	Scope     string
	Charter   []byte
	CreatedAt pgtype.Timestamptz
}
