// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package storegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendUtterance = `-- name: AppendUtterance :one
INSERT INTO utterances (id, ts, scope, payload) VALUES ($1, $2, $3, $4) RETURNING seq
`

type AppendUtteranceParams struct {
	ID      string
	Ts      pgtype.Timestamptz
	Scope   string
	Payload []byte
}

func (q *Queries) AppendUtterance(ctx context.Context, arg AppendUtteranceParams) (int64, error) {
	row := q.db.QueryRow(ctx, appendUtterance,
		arg.ID,
		arg.Ts,
		arg.Scope,
		arg.Payload,
	)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const closeExchange = `-- name: CloseExchange :exec
UPDATE exchanges SET state = $2, closed_at = $3 WHERE id = $1
`

type CloseExchangeParams struct {
	ID       string
	State    string
	ClosedAt pgtype.Timestamptz
}

func (q *Queries) CloseExchange(ctx context.Context, arg CloseExchangeParams) error {
	_, err := q.db.Exec(ctx, closeExchange, arg.ID, arg.State, arg.ClosedAt)
	return err
}

const insertPresence = `-- name: InsertPresence :exec
INSERT INTO presence_events (id, scope, voice, event, ts, expires_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPresenceParams struct {
	ID        string
	Scope     string
	Voice     string
	Event     string
	Ts        pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertPresence(ctx context.Context, arg InsertPresenceParams) error {
	_, err := q.db.Exec(ctx, insertPresence,
		arg.ID,
		arg.Scope,
		arg.Voice,
		arg.Event,
		arg.Ts,
		arg.ExpiresAt,
	)
	return err
}

const insertSettlement = `-- name: InsertSettlement :exec
INSERT INTO settlements (id, exchange_id, scope, terms, parties, ts) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSettlementParams struct {
	ID         string
	ExchangeID string
	Scope      string
	Terms      []byte
	Parties    []string
	Ts         pgtype.Timestamptz
}

func (q *Queries) InsertSettlement(ctx context.Context, arg InsertSettlementParams) error {
	_, err := q.db.Exec(ctx, insertSettlement,
		arg.ID,
		arg.ExchangeID,
		arg.Scope,
		arg.Terms,
		arg.Parties,
		arg.Ts,
	)
	return err
}

const listSettlements = `-- name: ListSettlements :many
SELECT id, exchange_id, terms, parties, ts FROM settlements WHERE scope = $1 ORDER BY ts DESC LIMIT $2
`

type ListSettlementsParams struct {
	Scope string
	Limit int32
}

type ListSettlementsRow struct {
	ID         string
	ExchangeID string
	Terms      []byte
	Parties    []string
	Ts         pgtype.Timestamptz
}

func (q *Queries) ListSettlements(ctx context.Context, arg ListSettlementsParams) ([]ListSettlementsRow, error) {
	rows, err := q.db.Query(ctx, listSettlements, arg.Scope, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettlementsRow
	for rows.Next() {
		var i ListSettlementsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExchangeID,
			&i.Terms,
			&i.Parties,
			&i.Ts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUtterancesSince = `-- name: ListUtterancesSince :many
SELECT seq, payload FROM utterances WHERE scope = $1 AND seq > $2 ORDER BY seq ASC LIMIT $3
`

type ListUtterancesSinceParams struct {
	Scope string
	Seq   int64
	Limit int32
}

type ListUtterancesSinceRow struct {
	Seq     int64
	Payload []byte
}

func (q *Queries) ListUtterancesSince(ctx context.Context, arg ListUtterancesSinceParams) ([]ListUtterancesSinceRow, error) {
	rows, err := q.db.Query(ctx, listUtterancesSince, arg.Scope, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUtterancesSinceRow
	for rows.Next() {
		var i ListUtterancesSinceRow
		if err := rows.Scan(&i.Seq, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openExchange = `-- name: OpenExchange :exec
INSERT INTO exchanges (id, scope, state, participants, opened_at) VALUES ($1, $2, 'open', $3, $4)
`

type OpenExchangeParams struct {
	ID           string
	Scope        string
	Participants []string
	OpenedAt     pgtype.Timestamptz
}

func (q *Queries) OpenExchange(ctx context.Context, arg OpenExchangeParams) error {
	_, err := q.db.Exec(ctx, openExchange,
		arg.ID,
		arg.Scope,
		arg.Participants,
		arg.OpenedAt,
	)
	return err
}

const purgeExpiredPresence = `-- name: PurgeExpiredPresence :execrows
DELETE FROM presence_events WHERE expires_at < $1
`

func (q *Queries) PurgeExpiredPresence(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredPresence, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertVoice = `-- name: UpsertVoice :exec
INSERT INTO voices (id, scope, charter) VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET charter = EXCLUDED.charter, scope = EXCLUDED.scope
`

type UpsertVoiceParams struct {
	ID      string
	Scope   string
	Charter []byte
}

func (q *Queries) UpsertVoice(ctx context.Context, arg UpsertVoiceParams) error {
	_, err := q.db.Exec(ctx, upsertVoice, arg.ID, arg.Scope, arg.Charter)
	return err
}
